Fix version attr module path with setuptools static attr parser
Setuptools attr parser does not support following imports which
results in setuptools falling back to dynamically executing the
module during a build which can break when runtime dependencies
are not yet present.

See:
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#attr

Fixes:
Traceback (most recent call last):
  File "/home/buildroot/buildroot/output/per-package/python-logbook/host/lib/python3.11/site-packages/setuptools/config/expand.py", line 193, in read_attr
    return getattr(StaticModule(module_name, spec), attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buildroot/buildroot/output/per-package/python-logbook/host/lib/python3.11/site-packages/setuptools/config/expand.py", line 87, in __getattr__
    raise AttributeError(f"{self.name} has no attribute {attr}") from e
AttributeError: logbook has no attribute __version__

Signed-off-by: James Hilliard <james.hilliard1@gmail.com>